### ISSUE TITLE
Data removed while in use

### ISSUE THREAD

**Issue by wattyrevBT** [licson0729/libSSE-php#10]
I have an application that I am building that, so far, basically creates isolated chat rooms. One user creates a chat room, then other people can join it.

I run into an issue where the chat room that was created disappears after maybe 10 minutes or so. I'm not sure if there is a predetermined way to change when a file is cleaned up or not, but I've had no luck finding it if it exists.

**Comment by wattyrevBT** [comment]
I've created a gist containing my code for creating the chat room, joining the room, sending the message, and listening to events:
https://gist.github.com/wattyrevBT/8eac9afb8f3e9449356a

**Comment by licson0729** [comment]
Oh. This is actually not an issue but rather a feature offered by libSSE.
The SSEData class will constantly remove unused keys say like 10 minutes. I
will update the library to expose the ability to disable this feature when
needed.

**Comment by wattyrevBT** [comment]
I figured it was something like that. Thanks! I'll keep an eye out for your update.

**Comment by licson0729** [comment]
It should br OK now if you create the `SSEData` object like this:

    $data = new SSEData('file',array('path'=>'./data', 'gc_lifetime' => 0));
