### ISSUE TITLE
Error in Utils::sseBlock()

### ISSUE THREAD

**Issue by Mithrillion** [licson0729/libSSE-php#13]
The parameter list is given as 
```
sseBlock($id, $data, $name = null)
```
However in SSE.php, it is called like:
```
Utils::sseBlock($this->id,$event,$data);
```
The parameters are not matched up.

**Comment by tonyhhyip** [comment]
@Mithrillion It is mostly my mistake, I forget to make a new release of this bug fixed, it was fixed

**Comment by licson0729** [comment]
Yes it is fixed in commit #484fe696f182dea7ccb4bc3b9b27147a7c55595d

**Comment by tonyhhyip** [comment]
@licson0729 It was fixed here 484fe696f182dea7ccb4bc3b9b27147a7c55595d

**Comment by Mithrillion** [comment]
I see that you have fixed the version on GitHub. However the version from Composer is still broken. I suppose it will be automatically updated shortly?

**Comment by tonyhhyip** [comment]
I will talk to @licson0729 about this

**Comment by tonyhhyip** [comment]
@Mithrillion version 2.0.1 is released, please update to this
