### ISSUE TITLE
How to use this library with Symfony 2.3

### ISSUE THREAD

**Issue by rajkaran** [licson0729/libSSE-php#15]
I have just installed this library through composer in my Symfony app. 
path to SSE class is `serverPushDemo\vendor\tonyhhyip\sse\src` where `serverPushDemo` is the name of my symfony app.

When I add `new  tonyhhyip\sse\src\SSE()` in `appkernel.php` file I am getting an error.

`FatalErrorException: Error: Class 'tonyhhyip\sse\src\SSE' not found in C:\xampp\htdocs\xtras\serverPushDemo\app\AppKernel.php line 22`

**Comment by tonyhhyip** [comment]
It is because you are using the wrong class namespace.
The correct namespace of libSSE is `Sse`.
To create a new instance, please use `new \Sse\SSE()`

**Comment by rajkaran** [comment]
So what I will be adding in appKernel?

**Comment by tonyhhyip** [comment]
I don't how to add it to the appKernel, I suppose it is added to the Controller.
Currently,  libSSE doesn't support for Symfony.
The Symfony Response is only supported in v2.1.0 which is in draft, you may wait for the release or install it by git.
```
class FooController extends Controller
{
   /**
    * @Route("/", name="home")
    */
   public function indexAction()
   {
       $sse = new \Sse\SSE();
       return $sse->createResponse();
    }
}
```
