### ISSUE TITLE
What about add support for RethinkDB?

### ISSUE THREAD

**Issue by edoz90** [licson0729/libSSE-php#16]
https://www.rethinkdb.com/

From the site:

> RethinkDB is the first open-source, scalable JSON database built from the ground up for the realtime web. It inverts the traditional database architecture by exposing an exciting new access model – instead of polling for changes, the developer can tell RethinkDB to continuously push updated query results to applications in realtime. RethinkDB’s realtime push architecture dramatically reduces the time and effort necessary to build scalable realtime apps.

**Comment by tonyhhyip** [comment]
@edoz90 thanks for giving this suggestion, can you tell me more about how you want RethinkDB to be support? I have no idea about how you want a RethinkDB to use in the libSSE-php

**Comment by tonyhhyip** [comment]
no more information and reply, close
