### ISSUE TITLE
Make server stream "new" data for 5 seconds only

### ISSUE THREAD

**Issue by victor-lund** [licson0729/libSSE-php#20]
Hello!

I just found this library so I haven't had a deep look into it yet - but it's nice to see an implementation of SSE's that actually does what it's suppose to do. Many implementation guides out there appears to use the SSE technique wrong, resulting in a setup not much different to polling? (https://www.html5rocks.com/en/tutorials/eventsource/basics/ for example).

Anyway, I have a question... I tried to force my server to only stream "new" data to the connected client for a limited time. Currently, it sends the latest data "forever" which is something i don't want.

My approach was to configure my EventHandler's **check**-method in such a way that it returns true only when the server's cache contains data. (All cache entries lives for only 5 seconds.)

EventHandler's **update** method was configured so that it returns the cache data (after json_encoding it).

Here is my server side code:

```
<?php
use Sse\Event;
use Sse\SSE;
use Sse\Data;

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once "../bootstrap.php";

//create the event handler
class MyEventHandler implements Event
{
    private $sseData;

    public function __construct()
    {
        $this->sseData = new Data('apcu');
    }

    public function update()
    {
        return json_encode(apcu_fetch('secretkey'));
    }

    public function check()
    {
        return apcu_exists('secretkey');
    }
}

$sse = new SSE(); //create a libSSE instance
$sse->allow_cors = true; //Allow cross-domain access? Default: false. If you want others to access this must set to
$sse->exec_limit = 0; //the execution time of the loop in seconds. Default: 600. Set to 0 to allow the script to run as long as possible.
$sse->use_chunked_encodung = true; //Use chunked encoding. Some server may get problems with this and it defaults to false
$sse->addEventListener('event_name', new MyEventHandler());//register your event handler
$sse->start();//start the event loop

```
So, this code does manage to capture new data from the server cache, however it does not prevent the server from sending the same old data after 5 seconds. Even if the cache is cleared, the last detected piece of data is sent "forever".

Is there a way to achieve this goal? The application i'm building requires notifications to be sent from the server to the client when these notifications are created (for example when a user logs in). I dont really want the "latest" notifications to be sent over and over again to the clients.

**Comment by licson0729** [comment]
Dear Victor,

There's actually [an example](https://github.com/licson0729/libSSE-php/blob/master/examples/chat/send.php) included in the library that uses the `SSE\Data` to detect and send updates only when necessary.

Generally, you should check updates by compare the time of the last message instead of simply checking the existence of a key. The code [here](https://github.com/licson0729/libSSE-php/blob/master/examples/chat/send.php#L36) may give you some hints.

**Comment by tonyhhyip** [comment]
You may add the ttl with [apcu_add](http://php.net/manual/en/function.apcu-add.php)

**Comment by victor-lund** [comment]
@licson0729 Brilliant! Thank's for the heads up - I should have read the examples more carefully.

It works just like i want it now.

I had to set the keep_alive constant quite low (it's now set to 10) since i kept getting: ERR_INCOMPLETE_CHUNKED_ENCODING when using the default value of 300.

Any clue why that is?
