### ISSUE TITLE
Is it possible to interface Sse to a Doctrine's listener?

### ISSUE THREAD

**Issue by neFAST** [licson0729/libSSE-php#22]
Hello,
I have played with this very nice bundle and implemented a test event that will return the number of records in a repository:

```
class RecentController extends Controller
{
    /**
     * @Route("/recent/records", name="recent/records")
     */
    public function sseAction()
    {
        $sse = new SSE();
        $sse->exec_limit = 10;
        $sse->sleep_time = 5;
        $sse->addEventListener('countChanged', new RecentEvent($this->getDoctrine()->getRepository('Bundle:Entity')));
        return $sse->createResponse();
    }
```

```
class RecentEvent implements Event
    {
    private $count = 0;   
    private $em;

    public function __construct(\Doctrine\ORM\EntityRepository $em)
    {
        $this->em = $em;
    }
    public function check()
    {
        $newCount = $this->em->createQueryBuilder('id')
                             ->select('COUNT(id)')
                             ->getQuery()
                             ->getSingleScalarResult();
        if( $newCount !== $this->count )
        {
            $this->count = $newCount;
            return true;
        }
        else
            return false;
    }
    
    public function update()
    {
        return $this->count;
    }
}
```

Now instead of "polling" the database to get the number of records, I would like to use a Doctrine listener on a `postPersist` event. Is it possible to go this way? Thanks in advance for your insights!

**Comment by tonyhhyip** [comment]
You can use plain SSE object with method `SSE::init` to initial and `SSE::sendBlock`, `SSE::flush` to send message and wrap the event listener in a Symfony StreamedResponse to send, hope this can solve the problem before I make out the push version

**Comment by neFAST** [comment]
In the mean time I have found a workaround using a magic $data adn something similar to your chat example.  
What's that push version you are talking about? Some new cool feature under development? 

```
    /**
    * @ORM\PrePersist
    */
    public function setSseData()
    {
        // Create a libSSE data instance, which is shared across all data instances 
        // in all PHP scripts. This allows easy cross-script communications for some of
        // the magic we done here.
        $data = new Data('file', array('path' => './data'));
        $data->set('user', json_encode(array(
		    'msg' => $this->firstName,
            'time' => time()
            )
        ));
    }
```

**Comment by tonyhhyip** [comment]
@neFAST I am studying on having SSE to connect with Symfony event, I am still handling some PHP problems and I don't have much time to work on it, so better not to expect it release in short time. You may try on [sse-react](https://github.com/clue/php-sse-react) for current

**Comment by neFAST** [comment]
Seems even more complex to integrate this one to Symfony (at least for a beginner like me).

**Comment by neFAST** [comment]
Hi @tonyhhyip 
I've again a bit of time to look at this. Could you just elaborate a little bit on how to use a plain SSE object with `SSE::sendBloc`? Thanks a lot

**Comment by licson0729** [comment]
There is a (internal but made public) method in `Sse\SSE` called `sendBlock` to emit an SSE event directly. Just call it like below:

```
$sse = new Sse\SSE();
$sse->init();

// On Doctrine listener update
$sse->sendBlock($event_id, $data, $event_name);
```

Beware if you're calling the library in this way you lose some of the capability like the event handlers and you must not call `$sse->start();` as this will block the script execution.

**Comment by neFAST** [comment]
Hi @tonyhhyip !
Any progress on that? Do you still plan to tackle that issue?
Thanks in advance

**Comment by tonyhhyip** [comment]
@neFAST No, I have no plan to tackle this issue. You are welcome to open PR on this

**Comment by neFAST** [comment]
OK, but you mentionned studying on having SSE to connect with Symfony event, have you given up?

**Comment by tonyhhyip** [comment]
I did studied before, but I failed to make it
