### ISSUE TITLE
Support for symfony?

### ISSUE THREAD

**Issue by DigiLive** [licson0729/libSSE-php#32]
Did you add support for symfony or do you require symfony?
I wanted to use it as a stand-alone package, but I see symfony namespaces and classes used by this package.

**Comment by licson0729** [comment]
Recent updates to the library now requires Symfony's HTTPFoundation to be installed for this library to work correctly. If you use this library through Compose, it should handle this dependency for you.

If you would like to use this as a standalone library, you will need to grab Symphony's HTTPFoundation class and include it along with libSSE to make it work as expected.

**Comment by fcools** [comment]
Aw... too bad for me. That's a lot of overhead for my small project. 
Do you know what it takes to remove this dependency while keeping the fixes regarding sse? I might fork the current branch and make it stand alone again.

**Comment by licson0729** [comment]
If you don't mind using an older version of the library with a less robust code base, you can fetch commit df44e80ba85568b802e5a2ed0b7cc9f3a6bc06b6 to your local machine and use that. It's the last commit before adding in the Symphony dependency.

**Comment by fcools** [comment]
Ok. Thanks. I'll take that commit and see if it needs updates or fixes of later commits.
