### ISSUE TITLE
session_start() make the page freeze.

### ISSUE THREAD

**Issue by alexwenbj** [licson0729/libSSE-php#33]
When I use session_start() to start a session,the page freeze!
```
session_start();

class YourEventHandler implements Event {...}
```
Would you please tell me how to use session in the libSSE?Thank you.

**Comment by alexwenbj** [comment]
After read the #4 and #8 issue,I think this is because the session block the page,but my question is: Where to put session_start() and session_write_close()?

**Comment by licson0729** [comment]
It depends on your case, but you always put `session_start()` at the top and use `session_write_close()` after you have finished dealing with session variables.

**Comment by alexwenbj** [comment]
> It depends on your case, but you always put `session_start()` at the top and use `session_write_close()` after you have finished dealing with session variables.

Thank you.I use the file instead of the session.
