### ISSUE TITLE
ajax posts loading taking too much time

### ISSUE THREAD

**Issue by Hsn0** [licson0729/libSSE-php#8]
in this library, it is conflicted with ajax posts, ajax requests taking too much time to complete with it.

it takes to load the same time as the loop takes to complete whatever you set the loop time.
I have set the $exec_limit = 3; $sleep_time = 1; and $client_reconnect = 2;
so why it is conflicting with ajax requests?

please fix this issue.

**Comment by licson0729** [comment]
Do you use sessions with your AJAX calls or SSE loops? If yes, you need to do a `session_write_close()` to release the PHP session lock that caused the issue.

**Comment by Hsn0** [comment]
what is the example of it?
I have separate php file where I send ajax requests.

**Comment by Hsn0** [comment]
thanks for giving me problems solution :smile:  hats off :smiley:

**Comment by ashnehete** [comment]
Where do I put the session_write_close()
The problem still persists and is slowing down the whole network.
All the network calls have a high TTFB (Time To First Byte)
