### ISSUE TITLE
Will the script stop if the user disconnects ?

### ISSUE THREAD

**Issue by daslicht** [licson0729/libSSE-php#9]
Will the script stop if the user disconnects ?
Is there a way to listen for user dis/connect

**Comment by p4ever** [comment]
seems that the script doesn't stop when the client is disconnected

**Comment by YamiOdymel** [comment]
[Take a look(http://stackoverflow.com/questions/28850986/how-can-i-stop-a-server-sent-event-script-from-running-when-the-user-closes-the)?]

> The PHP script should be killed as soon as the connection socket closes.
